scoreboard players random @s crates 1 30
execute @s[scores={crates=1}] ~~~ structure load common1 ~~~
execute @s[scores={crates=2}] ~~~ structure load common2 ~~~
execute @s[scores={crates=3}] ~~~ structure load common3 ~~~
execute @s[scores={crates=4}] ~~~ structure load common4 ~~~
execute @s[scores={crates=5}] ~~~ structure load common5 ~~~
execute @s[scores={crates=6}] ~~~ structure load common6 ~~~
execute @s[scores={crates=7}] ~~~ structure load common7 ~~~
execute @s[scores={crates=8}] ~~~ structure load common8 ~~~
execute @s[scores={crates=9}] ~~~ structure load common9 ~~~
execute @s[scores={crates=10}] ~~~ structure load common10 ~~~
execute @s[scores={crates=11}] ~~~ structure load common11 ~~~
execute @s[scores={crates=12}] ~~~ structure load common12 ~~~
execute @s[scores={crates=13}] ~~~ structure load common13 ~~~
execute @s[scores={crates=14}] ~~~ structure load common14 ~~~
execute @s[scores={crates=15}] ~~~ structure load common15 ~~~
execute @s[scores={crates=16}] ~~~ structure load common16 ~~~
execute @s[scores={crates=17}] ~~~ structure load common17 ~~~
execute @s[scores={crates=18}] ~~~ structure load common18 ~~~
execute @s[scores={crates=19}] ~~~ structure load common19 ~~~
execute @s[scores={crates=20}] ~~~ structure load common20 ~~~
execute @s[scores={crates=21}] ~~~ structure load common21 ~~~
execute @s[scores={crates=22}] ~~~ structure load common22 ~~~
execute @s[scores={crates=23}] ~~~ structure load common23 ~~~
execute @s[scores={crates=24}] ~~~ structure load common24 ~~~
execute @s[scores={crates=25}] ~~~ structure load common25 ~~~
execute @s[scores={crates=26}] ~~~ structure load common26 ~~~
execute @s[scores={crates=27}] ~~~ structure load common27 ~~~
execute @s[scores={crates=28}] ~~~ structure load common28 ~~~
execute @s[scores={crates=29}] ~~~ structure load common29 ~~~
execute @s[scores={crates=30}] ~~~ structure load common30 ~~~