scoreboard players random @s crates 1 30
execute @s[scores={crates=1}] ~~~ structure load legendary1 ~~~
execute @s[scores={crates=2}] ~~~ structure load legendary2 ~~~
execute @s[scores={crates=3}] ~~~ structure load legendary3 ~~~
execute @s[scores={crates=4}] ~~~ structure load legendary4 ~~~
execute @s[scores={crates=5}] ~~~ structure load legendary5 ~~~
execute @s[scores={crates=6}] ~~~ structure load legendary6 ~~~
execute @s[scores={crates=7}] ~~~ structure load legendary7 ~~~
execute @s[scores={crates=8}] ~~~ structure load legendary8 ~~~
execute @s[scores={crates=9}] ~~~ structure load legendary9 ~~~
execute @s[scores={crates=10}] ~~~ structure load legendary10 ~~~
execute @s[scores={crates=11}] ~~~ structure load legendary11 ~~~
execute @s[scores={crates=12}] ~~~ structure load legendary12 ~~~
execute @s[scores={crates=13}] ~~~ structure load legendary13 ~~~
execute @s[scores={crates=14}] ~~~ structure load legendary14 ~~~
execute @s[scores={crates=15}] ~~~ structure load legendary15 ~~~
execute @s[scores={crates=16}] ~~~ structure load legendary16 ~~~
execute @s[scores={crates=17}] ~~~ structure load legendary17 ~~~
execute @s[scores={crates=18}] ~~~ structure load legendary18 ~~~
execute @s[scores={crates=19}] ~~~ structure load legendary19 ~~~
execute @s[scores={crates=20}] ~~~ structure load legendary20 ~~~
execute @s[scores={crates=21}] ~~~ structure load legendary21 ~~~
execute @s[scores={crates=22}] ~~~ structure load legendary22 ~~~
execute @s[scores={crates=23}] ~~~ structure load legendary23 ~~~
execute @s[scores={crates=24}] ~~~ structure load legendary24 ~~~
execute @s[scores={crates=25}] ~~~ structure load legendary25 ~~~
execute @s[scores={crates=26}] ~~~ structure load legendary26 ~~~
execute @s[scores={crates=27}] ~~~ structure load legendary27 ~~~
execute @s[scores={crates=28}] ~~~ structure load legendary28 ~~~
execute @s[scores={crates=29}] ~~~ structure load legendary29 ~~~
execute @s[scores={crates=30}] ~~~ structure load legendary30 ~~~