scoreboard players random @s crates 1 30
execute @s[scores={crates=1}] ~~~ structure load rare1 ~~~
execute @s[scores={crates=2}] ~~~ structure load rare2 ~~~
execute @s[scores={crates=3}] ~~~ structure load rare3 ~~~
execute @s[scores={crates=4}] ~~~ structure load rare4 ~~~
execute @s[scores={crates=5}] ~~~ structure load rare5 ~~~
execute @s[scores={crates=6}] ~~~ structure load rare6 ~~~
execute @s[scores={crates=7}] ~~~ structure load rare7 ~~~
execute @s[scores={crates=8}] ~~~ structure load rare8 ~~~
execute @s[scores={crates=9}] ~~~ structure load rare9 ~~~
execute @s[scores={crates=10}] ~~~ structure load rare10 ~~~
execute @s[scores={crates=11}] ~~~ structure load rare11 ~~~
execute @s[scores={crates=12}] ~~~ structure load rare12 ~~~
execute @s[scores={crates=13}] ~~~ structure load rare13 ~~~
execute @s[scores={crates=14}] ~~~ structure load rare14 ~~~
execute @s[scores={crates=15}] ~~~ structure load rare15 ~~~
execute @s[scores={crates=16}] ~~~ structure load rare16 ~~~
execute @s[scores={crates=17}] ~~~ structure load rare17 ~~~
execute @s[scores={crates=18}] ~~~ structure load rare18 ~~~
execute @s[scores={crates=19}] ~~~ structure load rare19 ~~~
execute @s[scores={crates=20}] ~~~ structure load rare20 ~~~
execute @s[scores={crates=21}] ~~~ structure load rare21 ~~~
execute @s[scores={crates=22}] ~~~ structure load rare22 ~~~
execute @s[scores={crates=23}] ~~~ structure load rare23 ~~~
execute @s[scores={crates=24}] ~~~ structure load rare24 ~~~
execute @s[scores={crates=25}] ~~~ structure load rare25 ~~~
execute @s[scores={crates=26}] ~~~ structure load rare26 ~~~
execute @s[scores={crates=27}] ~~~ structure load rare27 ~~~
execute @s[scores={crates=28}] ~~~ structure load rare28 ~~~
execute @s[scores={crates=29}] ~~~ structure load rare29 ~~~
execute @s[scores={crates=30}] ~~~ structure load rare30 ~~~